### ISSUE TITLE
" gitcc rebase --load=.git/lshistory.bak " - results in Fatal Error

### ISSUE THREAD

**Issue by SabareeshSS** [charleso/git-cc#56]
Hi,
I am facing the following issue, as i can see the same issue faced by [andres] (https://github.com/charleso/git-cc/issues/5)

Can I get a solution for this Issue?

![image](https://cloud.githubusercontent.com/assets/7418432/6824723/b9b8d520-d31a-11e4-8cb8-9c7d07d8875b.png)

**Comment by charleso** [comment]
Hi @SabareeshSS,

Apologies. My error handling was simply terrible back then. There is probably a real error that is being masked by the one you're seeing. You need to go and modify the `rebase.py` `doCommit` function to print the exception before the `finally` block. Or comment out the line that is trying to create a branch in an empty repository. I'm sorry I can't help you more than that - I haven't touched this code in over 5 years.

Charles
