### ISSUE TITLE
Setup User.py

### ISSUE THREAD

**Issue by robbennett** [charleso/git-cc#62]
So I have change the user.py.example to User.py. And I've also added the code from the README.md into the user.py.
[core]
    include = FolderA|FolderB
    exclude = FolderA/sub/folder|FolderB/other/file
    debug = False
    type = UCM
    [master]
    clearcase = D:\views\co4222_flex\rd_poc
    branches = main|ji_dev|ji_*_dev|iteration_*_dev
    [sup]
    clearcase = D:\views\co4222_sup\rd_poc
    branches = main|sup

Now in my users.py under users I have it blank some of the people that has added code and comments are not with the company anymore so they don't have a git account. Now to the mailSuffix so I have that all set up with my company mailSuffix = 'example.com'. Now going down to the core I'm wanting to have everything from the VOB. So I have the include and exclude commented out. Is that wrong or right? For the branches I have this code. 
[DEV]
clearcase = c:\Users\RobBennett\Development_2 
branches = main|development
[PROD]
clearcase = c:\Users\RobBennett\Production_2
branches = main
So I'm in the folder that I place the new .git from ClearCase. I run the git init, that works, then I run gitcc init c:/Users/RobBennett/Development_2 (which is were my clearcase is located at) after that I end up with this error
gitcc init c:/Users/RobBennett/Development_2
	Traceback (most recent call last):
	File "c:/Users/RobBennett/Documents/git-cc-master/git-cc-master/gitcc:, line 4, in <module>
	import rebase, checkin, init, sync, reset, tag, update
	File "c:/Users/RobBennett/Documetns/git-cc-master/git-cc-master/rebase.py", line 7, in <module>
	from users import users, mailSuffix
	File "c:/Users/RobBennett/Documents/git-cc-master/git-cc-master/users.py", line 14
	cleasecase = C:/Users|RobBennett/Development_2
				^
SyntaxError: invalid syntax

So the major question is how do you set this thing up or do I have it set up correctly in order to get this to run. Or even when you do the gitcc init what path are you suppose to go to?

**Comment by charleso** [comment]
@robbennett Looks like you've copied/added the intended contents of the `.gitcc` configuration in to `users.py`. That's not going to work. It has to be valid python for starters.

I've said this previously, but I'm afraid git-cc is not very friendly. There's a good chance your going to hit a few more undocumented problems along the way. I haven't done work on git-cc in years, and I'm not sure I can help you. Apologies.
