### ISSUE TITLE
Not files after initial rebase

### ISSUE THREAD

**Issue by treaves** [charleso/git-cc#63]
I've no idea how to use ClearCase.  I've been asked to look at getting git-cc working.  I have followed the instructions here, and have fixed a couple of issues I've run into by looking over the issues list here.  But I still have no files.

The glitch rebase finishes and the lshistory.bak file is created.

The .git/gitcc file was pretty empty.  It had:
`[master]`
`clearcase = /cygdrive/v/p111000/app_root`

I added:
`BRANCHES=main|p111000_COL4.0`

main is the base 'branch'.  p111000_COL4.0 is my view.

Any 'git branch' leads to an error "fatal: Not a valid object name: 'Master'."  I see where several others have had this issue, and the advice was always that BRANCHES wasn't correct.  I see both of those when I run "clear tool lstype -kind brtype' and in the Clear Case explorer.  So I think it's correct.

I just can't seem to actually get the source code into my git directory to start work.

Any help would be appreciated.

**Comment by charleso** [comment]
Hi @treaves.

The error doesn't really tell you much unfortunately, it's just a sign that `git-cc` didn't import anything. I am curious though, is it "master" or "Master"? The latter seems very unusual. Also I'm assuming changing `BRANCHES` to `branches` doesn't work?

It might be handy to see some output from trying to import. And also perhaps a few lines from lshistory.bak, and in particular ones that contain `checkinversion` and a mention of one of your two branches.

Sorry I can't be more help.

**Comment by treaves** [comment]
It is 'master'.  Some of the auto correct of this browser hasn't helped.  Changing to lowercase 'branches' had not impact.

I reran all the commands, and the output is (the README doesn't actually show any branching operations, so I am assuming that after the gitcc rebase I should have the main branch checked out):

bash-4.3$ gitcc init /cygdrive/v/treaves_COL4.0/eqsys_col/
> git config core.autocrlf false
bash-4.3$ gitcc rebase
> git ls-files --modified
> cleartool update
> git log -n 1 --pretty=format:%ai master_cc
> cleartool ls -recurse -short .
> cleartool lsh -fmt %o%m|%Nd|%u|%En|%Vn|%Nc\n -recurse .
bash-4.3$ ls -la
\total 8
drwxr-xr-x+ 1 p603764 rt_eqsys 0 Feb 22 09:02 .
drwxr-xr-x+ 1 p603764 rt_eqsys 0 Feb 18 16:41 ..
drwxr-xr-x+ 1 p603764 rt_eqsys 0 Feb 22 09:08 .git
bash-4.3$ \



Some of the lines from the lshistory.bak file (my branch won't show, as I've never committed anything to this project before):
checkinversion|20160218.151804|p101111|web\emma_jboss\WebContent\app\js\setup\setup_emma.js|\main\COL4.0int\22|
checkinversion|20160218.151737|p101111|web\emma_jboss\WebContent\app\js\setup\setup_emma.js|\main\COL4.0int\jacob_COL4.0\1|
mkbranchversion|20160218.151621|p101111|web\emma_jboss\WebContent\app\js\setup\setup_emma.js|\main\COL4.0int\jacob_COL4.0\0|
mkbranchbranch|20160218.151621|p101111|web\emma_jboss\WebContent\app\js\setup\setup_emma.js|\main\COL4.0int\jacob_COL4.0|
checkinversion|20160218.132653|p101111|web\emma_jboss\WebContent\app\js\setup\setup_emma_ops.js|\main\COL4.0int\28|
checkinversion|20160218.132653|p101111|web\emma_jboss\WebContent\app\views\setup\setup_emma_ops.html|\main\COL4.0int\16|
checkinversion|20160218.132653|p101111|web\emma_jboss\WebContent\app\css\setup\setup_emma_ops.css|\main\COL4.0int\3|
checkinversion|20160218.132602|p101111|web\emma_jboss\WebContent\app\views\setup\setup_emma_ops.html|\main\COL4.0int\jacob_COL4.0\11|
checkinversion|20160218.132508|p101111|web\emma_jboss\WebContent\app\css\setup\setup_emma_ops.css|\main\jacob_COL4.0\4|
checkinversion|20160218.132346|p101111|web\emma_jboss\WebContent\app\js\setup\setup_emma_ops.js|\main\COL4.0int\jacob_COL4.0\17|
--cut--
checkindirectory version|20151113.020543|p101010|web\emma_jboss\WebContent\app\partials|\main\kordet_p101010_COL4.0\1|
mkbranchdirectory version|20151113.020543|p101010|web\emma_jboss\WebContent\app\partials|\main\kordet_p101010_COL4.0\0|
mkbranchbranch|20151113.020543|p101010|web\emma_jboss\WebContent\app\partials|\main\kordet_p101010_COL4.0|
mkelemdirectory version|20151113.020543|p101010|web\emma_jboss\WebContent\app\partials|\main\0|
mkelembranch|20151113.020543|p101010|web\emma_jboss\WebContent\app\partials|\main|
mkelemdirectory element|20151113.020543|p101010|web\emma_jboss\WebContent\app\partials||
--cut--
**null operation kind**file element|20151114.123734|p101010|web\emma_jboss\WebContent\app\js\kendo\kendo.columnsorter.min.js||
**null operation kind**file element|20151114.123731|p101010|web\emma_jboss\WebContent\app\js\kendo\kendo.columnmenu.min.js.map||

**Comment by treaves** [comment]
I think I've got past this issue.  I passed a different directory to the gitcc command
` /cygdrive/v/treaves_COL4.0/eqsys_col/web/emma_jboss/`
instead of
` /cygdrive/v/treaves_COL4.0/eqsys_col/`

Now, I'm getting an error when I run the  `gitcc update "Initial commit"` command.  It
s not finding a file.  I'll look into this a bit more.

**Comment by treaves** [comment]
I'm going to go ahead and close this, as I think the issue was that I specified the wrong directory, and the code doesn't correctly catch those types of user error, and end up hiding them.  If/when I get everything working, I may come back and write some error checking around this and submit a pull request.

**Comment by charleso** [comment]
@treaves Apologies, the error handling is non-existent. It wouldn't be hard to add either, it was shear laziness on my behalf all those years ago.
