### ISSUE TITLE
Can I use the program on Linux redhat?  

### ISSUE THREAD

**Issue by amousa1968** [charleso/git-cc#72]
Hello everyone, 
I am working on a mini project migrating clearcase by selecting a specific labels to git "bitbucket"  and the existing clearcase is running on linux and the new git will be running on linux too.    Does the program work on linux?   And would this migrate CC_labels to Git?

Thank you,
amousa1968

**Comment by charleso** [comment]
@amousa1968 Yes `git-cc` definitely works on linux.

> And would this migrate CC_labels to Git?

I'm afraid not. I never added label support to git-cc, sorry. :(

**Comment by amousa1968** [comment]
Thank you for the responses.   I am going to try the utility's this week and see how would I add label to the process.   Thank you. 

Thanks 
Ayman Mousa
