### ISSUE TITLE
Unable to understand workflow. Where to use git init and where to use gitcc init?

### ISSUE THREAD

**Issue by rhtpandeyIN** [charleso/git-cc#78]
Hi,

I am little confused after reading the workflow section of readme file.
Please help me to understand how to use git-cc properly.

Suppose my clearcase view directory is at location : /vbs/view/
then how to copy history of that view to a git repo?

Thanks in advance.

**Comment by charleso** [comment]
@rhtpandeyIN I'm sorry but I'm not sure I can help. As you've already seen, git-cc is very poorly documented and the code quality is no better. I can probably help you with initialisation, but there will almost certainly be problems and it will only get more frustrating. There are some good tickets on stackoverflow for how to sync clearcase to git that might be a safer place to start.

https://stackoverflow.com/questions/tagged/clearcase+git

**Comment by amousa1968** [comment]
Robit,  
I just saw your comments and the ticket has been closed.  Are you still want to migrate?    The use of git init step right after the code has been pulled of clearcase vob and you must tell git init process where you will be pushing large objects to?    Check my githut repo I have put something up under cc2git process.
