### ISSUE TITLE
Does git-cc support Git to CC

### ISSUE THREAD

**Issue by oplier** [charleso/git-cc#89]
Hi Charles,

I am reading the python code written by you and tried to run it. It's amazing. I synchronized CC data to Git successfully.

Could I know whether git-cc support to synchronize data from Git to CC?

Br,

**Comment by charleso** [comment]
@oplier Thanks. I'm not sure about "amazing", perhaps "amazingly bad", but when it works it can be handy. :)

Yes git-cc does support pushing from Git to CC. You can run `gitcc checkin` (I regret not calling it `push`).

**Comment by oplier** [comment]
Thank you Charles. I did the sync from Git to CC successfully, with "gitcc checkin --force" command~~

Besides, I learnt much knowledge of Python from your source, especially impressed by the design of calling Classes (such as "Modify", "Add" and "Delete") of "status.py" in "checkin.py"
